### ISSUE TITLE
https://share.streamlit.io/app/data-apps/ access not valid

### ISSUE THREAD

**Issue by wensenfriendandextra** [goldenrecursion/data-apps#8]
"You do not have access to this app or it does not exist" after I logged into the url above.

**Comment by aychang95** [comment]
@wensenfriendandextra 

I transferred this issue since it was posted in `predicates` instead of `data-apps` repo.

Good catch! The correct link is https://golden-data.streamlitapp.com/

The readme had the wrong link which is where I assumed you got the original broken link from. Let me know if this works for you
